#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # prepare vars
  local name="smartide"
  # files
  local tmp_file="$name"
  local bin_file="$tmp_file"

  if [ "$platform" = "darwin" ]; then
    platform="osx"
  fi

  # prepare context
  cd $tmp_dir

  # reference: https://smartidedl.blob.core.chinacloudapi.cn/releases
  # example:
  #   https://smartidedl.blob.core.chinacloudapi.cn/releases/1.0.25.5383/smartide-osx
  #   https://smartidedl.blob.core.chinacloudapi.cn/releases/1.0.25.5383/smartide-osx-arm64
  # generate url
  local url="https://smartidedl.blob.core.chinacloudapi.cn/releases/${PACKAGE_CORE_VERSION#v}/${name}-${platform}-${arch}"
  if [ "$platform" = "osx" ] && [ "$arch" = "amd64" ]; then
    url="https://smartidedl.blob.core.chinacloudapi.cn/releases/${PACKAGE_CORE_VERSION#v}/${name}-${platform}"
  fi

  log::debug "[package][$name][$kernel][$arch] url: $url"

  # download
  os::download $tmp_file $url

  # make executable
  chmod +x $tmp_file

  # install
  sudo mv $bin_file $usr_bin_dir

  # clean
  rm -rf $tmp_dir
}

export -f install
